### ISSUE TITLE
Mac OS X Installation

### ISSUE THREAD

**Issue by igoumeninja** [ks1f14s/la-kenak#1]
Καλησπέρα και συγχαρητήρια για την προσπάθεια,
Προσπαθώ να εγκαταστήσω το la-kenak στο Mac OS X 10.10.1 και αντιμτωπίζω τα παρακάτω προβλήματα:
Όταν βρίσκομαι στη σελίδα http://localhost/kenakv3/
![screen shot 2015-02-25 at 2 30 38 pm](https://cloud.githubusercontent.com/assets/155644/6370873/f49c087a-bcfd-11e4-8334-fa58e3de42f1.png)

παίρνω αρχικά ένα warning (στο πάνω μέρος της σελίδας): 
_Warning: mysql_connect(): Access denied for user 'root'@'localhost' (using password: YES) in /Applications/XAMPP/xamppfiles/htdocs/kenakv3/includes/connection.php on line 29
﻿ February 25, 2015, 1:41 pm_

και όταν πατάω εγκατασταση με χρήστη *admin* και κωδικό *admin* πέρνω τα αποτελέσματα 
![screen shot 2015-02-25 at 2 36 12 pm](https://cloud.githubusercontent.com/assets/155644/6370686/ad9de210-bcfb-11e4-8e46-14bbc61c6f7f.png)
Μπορείς να καταλάβεις γιατί;

Ευχαριστώ προκαταβολικά
Άρης

Y.Γ. Χρησιμοποίησα για να βάλω password την παρακάτω σελίδα https://www.apachefriends.org/faq_osx.html

**Comment by ks1f14s** [comment]
1. Αρχικά τροποποίησε το αρχείο database.php με το username και τον κωδικό που έχεις ορίσει για τη βάση δεδομένων.
2. Χρησιμοποίησε το phpmyadmin το οποίο έρχεται μαζί με το xampp και δημιούργησε τη βάση δεδομένων χειροκίνητα. Βάλε όποιο όνομα θες για τη βάση και μετά κάνε import το αρχείο sql που θα βρεις στο φάκελο /install σε αυτή τη βάση που έφτιαξες. Θα σου δημιουργήσει τους πίνακες και θα δεις τη βάση δεδομένων γεμάτη. Το όνομα της βάσης πρέπει να το δηλώσεις και στο database.php.

Δες και αυτό το video. Είναι κατατοπιστικό για χειροκίνητη εγκατάσταση. Μη σε απασχολεί ότι στο βίντεο το έκανα σε windows. Η διαδικασία είναι παρόμοια σε macos. 
https://www.youtube.com/watch?v=l5J2FoFsesA
