### ISSUE TITLE
problima sto lakenan 

### ISSUE THREAD

**Issue by giorgio616** [ks1f14s/la-kenak#2]
εχω windows 8.1 
xampp v3.2.2. 
http://sourceforge.net/projects/lakenak/files/  κατεβασα την v3 απο εδω 
σημερα παω στη διεύθυνση http://localhost/kenakv3  αλλα δεν μπορω να συνδεθω καν ...
καποιο λαθος εχω κανει σιγουρα.... τις προαλες χωρις να εχω κανει κατι διαφορετικο μου εβγαζε αυτα οταν εκανα την εγκατασταση μεσα απο τον μοζιλα 
Notice: Undefined index: periexomeno in C:\xampp\htdocs\kenakv3\install\install_script.php on line 33
Warning: fclose() expects parameter 1 to be resource, string given in C:\xampp\htdocs\kenakv3\install\install_script.php on line 42
Τα στοιχεία που δώσατε προστέθηκαν στο αρχείο includes/database.php. Πατήστε έναρξη εισαγωγής παρακάτω...﻿﻿﻿
Notice: Constant DB_SERVER already defined in C:\xampp\htdocs\kenakv3\includes\database.php on line 27
Notice: Constant DB_USER already defined in C:\xampp\htdocs\kenakv3\includes\database.php on line 28
Notice: Constant DB_PASS already defined in C:\xampp\htdocs\kenakv3\includes\database.php on line 29
Notice: Constant DB_NAME already defined in C:\xampp\htdocs\kenakv3\includes\database.php on line 30
Notice: Constant VERSION already defined in C:\xampp\htdocs\kenakv3\includes\database.php on line 31
Notice: Constant VERSION_ΤΕΕ already defined in C:\xampp\htdocs\kenakv3\includes\database.php on line 32
Warning: mysql_connect(): Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\kenakv3\includes\connection.php on line 29
Warning: include_once(install/install.php): failed to open stream: No such file or directory in C:\xampp\htdocs\kenakv3\includes\connection.php on line 32
Warning: include_once(): Failed opening 'install/install.php' for inclusion (include_path='.;\xampp\php\PEAR') in C:\xampp\htdocs\kenakv3\includes\connection.php on line 32

ευχαριστω

**Comment by ks1f14s** [comment]
1. Κατέβασε από εδώ (git) για την πλέον πρόσφατη έκδοση
2. Ακολούθησε τα βήματα που αναφέρονται στο βίντεο εδώ: 
https://www.youtube.com/watch?v=l5J2FoFsesA 
τα οποία αφορούν χειροκίνητη εγκατάσταση. Τα εξηγώ αναλυτικά εκεί. 

2. Τροποποίησε το αρχείο php.ini του xampp (βρίσκεται στο φάκελο php του xampp) για να γλιτώσεις από τα λάθη.
3. Έλεγξε ξανά ότι ο κωδικός που έχεις για τη βάση δεδομένων είναι σωστός στο αρχείο database.php
4. Έλεγξε ότι το xampp λειτουργεί σωστά. Θα πρέπει apache και mysql να τρέχουν κανονικά (πράσινα) στις θύρες 80 και 3306 αντίστοιχα. Αν όχι κάποιο άλλο πρόγραμμα τρέχει σε αυτές τις θύρες (πχ skype, teamviewer, vmware κλπ). Κλείστα προσωρινά. 
5. Ως έσχατη λύσει κατέβασε την portable έκδοση του la-kenak v3 η οποία λειτουργεί off-the-box. Απλά αντιγράφεις το φάκελο στο c: ή σε κάποιο στικάκι, τρέχεις το exe και λειτουργεί κατευθείαν.

**Comment by giorgio616** [comment]
εγινε ... παρα πολυ καλη δουλεια ... μπραβο ... ισως πρεπει να σκεφτεις η 4 εκδοση να εχει ενα μικρο αντιτημο ... ισως εθελοντικα το αξιζει η δουλεια σου...

**Comment by ks1f14s** [comment]
Χαίρομαι που βοήθησα. Στην επόμενη έκδοση θα είναι πιο ευκολα τα πράγματα γιατί επανασχεδιάστηκε από την αρχή. 
Ίσως όταν ολοκληρωθεί η 4 να μπει κάτι ως donation για τον κόπο υλοποίησης και την υποστήριξη. Πάντως το λογισμικό είναι χωρίς χρέωση και θα παραμείνει.
